"""Scope document (project charter, 10 fixed sections) as DOCX and PDF."""
import io
from datetime import date

from ..defaults import PARAMETERS, PHASES, VARIANTS
from ..estimation import normalize_params

L = {
    "de": {
        "title": "Scope-Dokument",
        "subtitle": "Projektcharta gemäß ReqPOOL Estimation Manager",
        "s1": "1. Projektname & Auftraggeber",
        "s2": "2. Projektziel & Nutzen",
        "s3": "3. Scope-Parameter",
        "s4": "4. Function-Point-Aufstellung (IFPUG)",
        "s5": "5. Aufwands- und Kostenübersicht",
        "s6": "6. Betriebs- & Beratungsaufwand",
        "s7": "7. Annahmen & Rahmenbedingungen",
        "s8": "8. Out-of-Scope",
        "s9": "9. Scope-Historie",
        "s10": "10. Freigabe",
        "project": "Projektname", "client": "Auftraggeber", "date": "Datum",
        "version": "Version", "goal": "Projektziel", "benefit": "Nutzen",
        "parameter": "Parameter", "count": "Anzahl", "definition": "Definition",
        "ifpug_type": "IFPUG-Typ", "counted": "Gezählt", "weight": "Gewicht",
        "complexity": "Komplexität", "fp": "FP",
        "unadjusted": "Unadjusted FP", "vaf": "Value Adjustment Factor",
        "adjusted": "Adjusted FP",
        "variant": "Variante", "hours": "Stunden", "cost": "Kosten (EUR)",
        "best": "Best Case", "expected": "Expected", "worst": "Worst Case",
        "phase": "Phase", "share": "Anteil",
        "operations": "Betriebsaufwand p.a.", "consulting": "Beratungsaufwand",
        "of_implementation": "vom Umsetzungsaufwand",
        "tokens": "Geschätzter KI-Token-Verbrauch (agentisch)",
        "session": "Session", "fp_total": "FP gesamt", "note": "Anmerkung",
        "sign_client": "Auftraggeber (Datum, Unterschrift)",
        "sign_contractor": "Auftragnehmer (Datum, Unterschrift)",
        "none": "Keine Angaben.",
        "no_sessions": "Noch keine Scope-Sessions vorhanden.",
        "productivity": "Produktivität",
        "complexity_low": "niedrig", "complexity_average": "mittel", "complexity_high": "hoch",
    },
    "en": {
        "title": "Scope Document",
        "subtitle": "Project charter generated by ReqPOOL Estimation Manager",
        "s1": "1. Project Name & Client",
        "s2": "2. Project Goal & Benefit",
        "s3": "3. Scope Parameters",
        "s4": "4. Function Point Breakdown (IFPUG)",
        "s5": "5. Effort & Cost Overview",
        "s6": "6. Operations & Consulting Effort",
        "s7": "7. Assumptions & Constraints",
        "s8": "8. Out of Scope",
        "s9": "9. Scope History",
        "s10": "10. Approval",
        "project": "Project name", "client": "Client", "date": "Date",
        "version": "Version", "goal": "Project goal", "benefit": "Benefit",
        "parameter": "Parameter", "count": "Count", "definition": "Definition",
        "ifpug_type": "IFPUG type", "counted": "Counted", "weight": "Weight",
        "complexity": "Complexity", "fp": "FP",
        "unadjusted": "Unadjusted FP", "vaf": "Value adjustment factor",
        "adjusted": "Adjusted FP",
        "variant": "Variant", "hours": "Hours", "cost": "Cost (EUR)",
        "best": "Best case", "expected": "Expected", "worst": "Worst case",
        "phase": "Phase", "share": "Share",
        "operations": "Operations effort p.a.", "consulting": "Consulting effort",
        "of_implementation": "of implementation effort",
        "tokens": "Estimated AI token consumption (agentic)",
        "session": "Session", "fp_total": "Total FP", "note": "Note",
        "sign_client": "Client (date, signature)",
        "sign_contractor": "Contractor (date, signature)",
        "none": "Not specified.",
        "no_sessions": "No scope sessions yet.",
        "productivity": "Productivity",
        "complexity_low": "low", "complexity_average": "average", "complexity_high": "high",
    },
}


def _fmt(n: float) -> str:
    return f"{n:,.0f}".replace(",", ".")  # 12.345 (EU grouping)


def _param_label(key: str, lang: str) -> str:
    p = next(p for p in PARAMETERS if p["key"] == key)
    return p["label"][lang]


def _phase_label(key: str, lang: str) -> str:
    p = next(p for p in PHASES if p["key"] == key)
    return p[lang]


def _variant_label(key: str, lang: str) -> str:
    v = next(v for v in VARIANTS if v["key"] == key)
    return v[lang]


def build_scope_data(project, sessions, results: dict, lang: str = "de") -> dict:
    """Language-resolved content model consumed by the DOCX and PDF renderers."""
    t = L[lang]
    params = normalize_params(
        (sessions[-1].params if sessions else project.params) or {}
    )
    fp = results["function_points"]
    version = f"{sessions[-1].version}.0" if sessions else "0.1"

    param_rows = [
        [_param_label(p["key"], lang), str(params[p["key"]]), p["definition"][lang]]
        for p in PARAMETERS
    ]

    fp_rows = [
        [
            _param_label(c["param"], lang), c["ifpug_type"], str(c["count"]),
            str(c["effective_count"]), t.get(f"complexity_{c['complexity']}", c["complexity"]),
            str(c["weight"]), _fmt(c["fp"]),
        ]
        for c in fp["components"]
    ]

    variant_rows, phase_rows, ops_rows = [], [], []
    for vkey in ("classic", "agile", "agentic"):
        v = results["variants"][vkey]
        variant_rows.append([
            _variant_label(vkey, lang), f"{v['hours_per_fp']} h/FP",
            _fmt(v["hours"]["best"]), _fmt(v["hours"]["expected"]), _fmt(v["hours"]["worst"]),
            _fmt(v["cost"]["expected"]),
        ])
        for ph in PHASES:
            p = v["phases"][ph["key"]]
            phase_rows.append([
                _variant_label(vkey, lang), _phase_label(ph["key"], lang),
                f"{p['pct']:.0f} %", _fmt(p["hours"]), _fmt(p["cost"]),
            ])
        ops_rows.append([
            _variant_label(vkey, lang),
            f"{v['operations']['pct_pa']:.0f} % {t['of_implementation']}",
            _fmt(v["operations"]["annual_cost"]),
            f"{v['consulting']['pct']:.0f} % {t['of_implementation']}",
            _fmt(v["consulting"]["cost"]),
        ])

    tokens = results["tokens"]
    token_line = (
        f"{t['tokens']}: {_fmt(tokens['total_tokens'])} Tokens "
        f"({_fmt(tokens['tokens_per_fp'])} Tokens/FP, "
        f"{tokens['price_per_million_eur']} EUR/1M) = {_fmt(tokens['cost'])} EUR"
    )

    history_rows = [
        [
            str(s.version), s.name, s.created_at.date().isoformat(),
            ", ".join(f"{_param_label(k, lang)}: {v}" for k, v in normalize_params(s.params).items() if v),
            _fmt(s.results["function_points"]["adjusted"]),
        ]
        for s in sessions
    ]

    assumptions = [a[lang] for a in results["assumptions"]]
    if project.assumptions:
        assumptions.append(project.assumptions)

    return {
        "t": t,
        "title": t["title"],
        "meta": [
            (t["project"], project.name),
            (t["client"], project.client or "—"),
            (t["date"], date.today().isoformat()),
            (t["version"], version),
        ],
        "goal": project.goal or t["none"],
        "benefit": project.benefit or t["none"],
        "param_header": [t["parameter"], t["count"], t["definition"]],
        "param_rows": param_rows,
        "fp_header": [t["parameter"], t["ifpug_type"], t["count"], t["counted"],
                      t["complexity"], t["weight"], t["fp"]],
        "fp_rows": fp_rows,
        "fp_summary": [
            (t["unadjusted"], _fmt(fp["unadjusted"])),
            (t["vaf"], f"{fp['vaf']:.2f}"),
            (t["adjusted"], _fmt(fp["adjusted"])),
        ],
        "variant_header": [t["variant"], t["productivity"], f"{t['hours']} ({t['best']})",
                           f"{t['hours']} ({t['expected']})", f"{t['hours']} ({t['worst']})",
                           f"{t['cost']} ({t['expected']})"],
        "variant_rows": variant_rows,
        "phase_header": [t["variant"], t["phase"], t["share"], t["hours"], t["cost"]],
        "phase_rows": phase_rows,
        "ops_header": [t["variant"], t["operations"], t["cost"], t["consulting"], t["cost"]],
        "ops_rows": ops_rows,
        "token_line": token_line,
        "assumptions": assumptions,
        "out_of_scope": project.out_of_scope or t["none"],
        "history_header": [t["version"], t["session"], t["date"], t["parameter"], t["fp_total"]],
        "history_rows": history_rows,
        "no_sessions": t["no_sessions"],
        "signatures": [t["sign_client"], t["sign_contractor"]],
    }


# --- DOCX --------------------------------------------------------------------

def render_docx(data: dict) -> bytes:
    from docx import Document
    from docx.shared import Pt

    doc = Document()
    t = data["t"]

    doc.add_heading(data["title"], level=0)
    doc.add_paragraph(t["subtitle"])

    def table(header, rows):
        tab = doc.add_table(rows=1, cols=len(header))
        tab.style = "Light Grid Accent 1"
        for i, h in enumerate(header):
            cell = tab.rows[0].cells[i]
            cell.text = h
            for run in cell.paragraphs[0].runs:
                run.bold = True
        for row in rows:
            cells = tab.add_row().cells
            for i, val in enumerate(row):
                cells[i].text = str(val)
        return tab

    doc.add_heading(t["s1"], level=1)
    table(["", ""], data["meta"])

    doc.add_heading(t["s2"], level=1)
    doc.add_paragraph(f"{t['goal']}: {data['goal']}")
    doc.add_paragraph(f"{t['benefit']}: {data['benefit']}")

    doc.add_heading(t["s3"], level=1)
    table(data["param_header"], data["param_rows"])

    doc.add_heading(t["s4"], level=1)
    table(data["fp_header"], data["fp_rows"])
    for label, value in data["fp_summary"]:
        p = doc.add_paragraph()
        p.add_run(f"{label}: ").bold = True
        p.add_run(value)

    doc.add_heading(t["s5"], level=1)
    table(data["variant_header"], data["variant_rows"])
    doc.add_paragraph()
    table(data["phase_header"], data["phase_rows"])

    doc.add_heading(t["s6"], level=1)
    table(data["ops_header"], data["ops_rows"])
    doc.add_paragraph(data["token_line"])

    doc.add_heading(t["s7"], level=1)
    for a in data["assumptions"]:
        doc.add_paragraph(a, style="List Bullet")

    doc.add_heading(t["s8"], level=1)
    doc.add_paragraph(data["out_of_scope"])

    doc.add_heading(t["s9"], level=1)
    if data["history_rows"]:
        table(data["history_header"], data["history_rows"])
    else:
        doc.add_paragraph(data["no_sessions"])

    doc.add_heading(t["s10"], level=1)
    for sig in data["signatures"]:
        doc.add_paragraph("\n\n_________________________________")
        p = doc.add_paragraph(sig)
        p.runs[0].font.size = Pt(9)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


# --- PDF ---------------------------------------------------------------------

def render_pdf(data: dict) -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import (Paragraph, SimpleDocTemplate, Spacer, Table,
                                    TableStyle)

    t = data["t"]
    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("H1", parent=styles["Heading1"], textColor=colors.black, spaceBefore=14)
    body = styles["BodyText"]
    small = ParagraphStyle("Small", parent=body, fontSize=8, leading=10)

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm,
                            topMargin=18 * mm, bottomMargin=18 * mm,
                            title=f"{data['title']} - {dict(data['meta'])[t['project']]}")
    story = [Paragraph(data["title"], styles["Title"]),
             Paragraph(t["subtitle"], body), Spacer(1, 6)]

    grid = TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#9a9a9a")),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#111111")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
    ])
    plain = TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#9a9a9a")),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ])

    def para_rows(rows):
        return [[Paragraph(str(c), small) for c in row] for row in rows]

    def add_table(header, rows, widths=None):
        story.append(Table([header] + para_rows(rows), style=grid, colWidths=widths,
                           repeatRows=1))
        story.append(Spacer(1, 6))

    story.append(Paragraph(t["s1"], h1))
    story.append(Table(data["meta"], style=plain, colWidths=[45 * mm, None]))

    story.append(Paragraph(t["s2"], h1))
    story.append(Paragraph(f"<b>{t['goal']}:</b> {data['goal']}", body))
    story.append(Paragraph(f"<b>{t['benefit']}:</b> {data['benefit']}", body))

    story.append(Paragraph(t["s3"], h1))
    add_table(data["param_header"], data["param_rows"], widths=[35 * mm, 15 * mm, None])

    story.append(Paragraph(t["s4"], h1))
    add_table(data["fp_header"], data["fp_rows"])
    for label, value in data["fp_summary"]:
        story.append(Paragraph(f"<b>{label}:</b> {value}", body))

    story.append(Paragraph(t["s5"], h1))
    add_table(data["variant_header"], data["variant_rows"])
    add_table(data["phase_header"], data["phase_rows"])

    story.append(Paragraph(t["s6"], h1))
    add_table(data["ops_header"], data["ops_rows"])
    story.append(Paragraph(data["token_line"], body))

    story.append(Paragraph(t["s7"], h1))
    for a in data["assumptions"]:
        story.append(Paragraph(f"• {a}", body))

    story.append(Paragraph(t["s8"], h1))
    story.append(Paragraph(data["out_of_scope"], body))

    story.append(Paragraph(t["s9"], h1))
    if data["history_rows"]:
        add_table(data["history_header"], data["history_rows"],
                  widths=[15 * mm, 30 * mm, 22 * mm, None, 18 * mm])
    else:
        story.append(Paragraph(data["no_sessions"], body))

    story.append(Paragraph(t["s10"], h1))
    for sig in data["signatures"]:
        story.append(Spacer(1, 24))
        story.append(Paragraph("_________________________________", body))
        story.append(Paragraph(sig, small))

    doc.build(story)
    return buf.getvalue()
